apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-go
spec:
  selector:
    matchLabels:
      app: gitops-go
  template:
    metadata:
      labels:
        app: gitops-go
    spec:
      containers:
      - name: gitops-go
        image: gitops-go
        ports:
        - containerPort: 8080
