apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: gitops-go
  newName: kevencript/gitops-go
  newTag: e2eb135589bd6cb347ff2c42c9ce320b05944b53
