name: CD Gitops

on:
  push:
    branches: [main]

steps:
- name: Checkout Github
  uses: actions/checkout@v3

- name: Build & Push image to Dockerhub
  uses: docker/build-push-action@1.1.0
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    repository: ${{ secrets.DOCKER_USERNAME }}/gitops-go
    tags: ${{ github.sha }}, latest

